### ISSUE TITLE
On chrome/MBP with touch ID I can register with finger print, but can't log in with finger print

### ISSUE THREAD

**Issue by richbradshaw** [davidearl/webauthn#26]
As title - register allows me to use the finger print sensor, but on log in, Chrome's UI requires me to use a USB security key. Chrome 77, MacOS 10.14.6.

**Comment by davidearl** [comment]
Thanks. I suspect the list of transports currently at line 247 of WebAuthn.php has been extended since this was written, so 
`$allow->transports = array('usb','nfc','ble');`
Should probably be
`$allow->transports = array('usb','nfc','ble','internal');`

I don’t have a Mac with a fingerprint reader. If I make this change tomorrow, might you be able to test it for me? I’m assuming you’re using webauthn.savesnine.info, but if you have set up your own server, you could try that change yourself, of course.

**Comment by davidearl** [comment]
I've made that change now in https://webauthn.savesnine.info (not on github yet). If you have a chance to try it, that would be very helpful. (I'm only speculating this is the problem, but it seems quite likely. Curiously the Android fingerprint reader works without this)

**Comment by richbradshaw** [comment]
Thanks a lot! That works great!

Thanks a lot!
